apiVersion: v1
kind: ReplicationController
metadata:
   name: replicationcontroller
spec:
   replicas: 3 
   selector:
     app: nginx
   template:
     metadata:
       name: Replication
       labels:
         app: nginx
     spec:
       containers:
       - name: nginx
         image: ravitejakumar/raviwebsite 
         ports:
         - name: nginx
           containerPort: 80
         imagePullPolicy: Always
